/*
 * This source file was generated by the Gradle 'init' task
 */
package lib4150;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void DigSRFlipFLop01() {
        DigSRFlipFlop classUnderTest = new DigSRFlipFlop();
        assertFalse(classUnderTest.SRFlipFlopValue(), "Set Reset Flip Flop getValue 'false'");
    }
}
